// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXw7vQzyExpoDeMpBVbLSWZea7n8C1adM',
    appId: '1:720816038024:web:5b4ed00a25c333dd0cbf3d',
    messagingSenderId: '720816038024',
    projectId: 'alidiamond-78f95',
    authDomain: 'alidiamond-78f95.firebaseapp.com',
    storageBucket: 'alidiamond-78f95.firebasestorage.app',
    measurementId: 'G-J11XRX8QLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyB3SPQHgamNUaoyCeuKmm3X1Ts3n_cgY',
    appId: '1:720816038024:android:d9f0af03f1d0830b0cbf3d',
    messagingSenderId: '720816038024',
    projectId: 'alidiamond-78f95',
    storageBucket: 'alidiamond-78f95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkj17gg518nUXowbDZvEXigeEntc_KhGE',
    appId: '1:720816038024:ios:993e0c9bfd328cbc0cbf3d',
    messagingSenderId: '720816038024',
    projectId: 'alidiamond-78f95',
    storageBucket: 'alidiamond-78f95.firebasestorage.app',
    iosBundleId: 'com.example.personalPudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkj17gg518nUXowbDZvEXigeEntc_KhGE',
    appId: '1:720816038024:ios:993e0c9bfd328cbc0cbf3d',
    messagingSenderId: '720816038024',
    projectId: 'alidiamond-78f95',
    storageBucket: 'alidiamond-78f95.firebasestorage.app',
    iosBundleId: 'com.example.personalPudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXw7vQzyExpoDeMpBVbLSWZea7n8C1adM',
    appId: '1:720816038024:web:4be595c458dddd980cbf3d',
    messagingSenderId: '720816038024',
    projectId: 'alidiamond-78f95',
    authDomain: 'alidiamond-78f95.firebaseapp.com',
    storageBucket: 'alidiamond-78f95.firebasestorage.app',
    measurementId: 'G-HJQTVVCXLN',
  );
}
